// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e6c5dc68-5be7-4dad-b166-9bb3647c62a0",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_L6PEfsXZM",
    "aws_user_pools_web_client_id": "7hfm4tn0rdj3ckohntafe15s0u",
    "oauth": {},
    "aws_user_files_s3_bucket": "ownspacemobile97f1dc2026c74db38c9da6caae4c290c204709-ownspace",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
